namespace PaketLoadScripts

#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Http.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.WebUtilities.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Configuration.Binder.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Logging.Abstractions.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Options.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Net.Http.Headers.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Memory.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Numerics.Vectors.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Runtime.CompilerServices.Unsafe.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Security.Cryptography.Cng.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Threading.Tasks.Extensions.fsx" 
#r "/Users/chethusk/.nuget/packages/microsoft.aspnetcore.server.kestrel.core/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll" 