namespace PaketLoadScripts

#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Authentication.Core.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Http.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.HttpOverrides.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Logging.Abstractions.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Options.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Buffers.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.IO.Pipelines.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Memory.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Numerics.Vectors.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Runtime.CompilerServices.Unsafe.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Security.Principal.Windows.fsx" 
#r "/Users/chethusk/.nuget/packages/microsoft.aspnetcore.server.iisintegration/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.IISIntegration.dll" 