namespace PaketLoadScripts

#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Http.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Configuration.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Configuration.EnvironmentVariables.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Configuration.FileExtensions.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.DependencyInjection.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.FileProviders.Physical.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Hosting.Abstractions.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Logging.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Options.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Diagnostics.DiagnosticSource.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Reflection.Metadata.fsx" 
#r "/Users/chethusk/.nuget/packages/microsoft.aspnetcore.hosting/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Hosting.dll" 