namespace PaketLoadScripts

#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Giraffe.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Antiforgery.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Authentication.Cookies.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Authentication.JwtBearer.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Authentication.OAuth.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Authorization.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Cors.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.ResponseCompression.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Rewrite.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.Session.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.AspNetCore.StaticFiles.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/Microsoft.Extensions.Caching.Memory.fsx" 
#r "/Users/chethusk/.nuget/packages/saturn/0.8.0/lib/netstandard2.0/Saturn.dll" 