namespace PaketLoadScripts

#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Collections.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Diagnostics.Debug.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Diagnostics.Tracing.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Globalization.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.IO.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Net.Http.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Net.Primitives.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Net.WebHeaderCollection.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Resources.ResourceManager.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Runtime.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Threading.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Threading.Tasks.fsx" 
#r "System" 