namespace PaketLoadScripts

#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Collections.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Diagnostics.Debug.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Diagnostics.Tracing.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Globalization.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.IO.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Net.Http.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Net.Primitives.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Net.WebHeaderCollection.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Resources.ResourceManager.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Runtime.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Threading.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Threading.Tasks.csx" 
#r "System" 