namespace PaketLoadScripts

#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Collections.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Diagnostics.Debug.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Diagnostics.Tools.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Globalization.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.IO.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Reflection.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Resources.ResourceManager.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Runtime.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Runtime.Extensions.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Text.Encoding.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Threading.csx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Xml.ReaderWriter.csx" 
#r "System.Xml.Linq" 