namespace PaketLoadScripts

#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Buffers.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Collections.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Diagnostics.Debug.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.IO.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Resources.ResourceManager.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Runtime.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Runtime.Extensions.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Runtime.Handles.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Runtime.InteropServices.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Text.Encoding.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Threading.fsx" 
#load "/Users/chethusk/oss/computation-expressions-workshop/.paket/load/net471/System.Threading.Tasks.fsx" 
#r "System" 
#r "/Users/chethusk/.nuget/packages/system.io.compression/4.3.0/lib/net46/System.IO.Compression.dll" 